version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - csnet
    environment: #sets up the database
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  # Python, Flask, Gunicorn
  app:
    container_name: app
    build: ./app
    restart: always
    ports:
      - 5050:5050
    depends_on: 
      - 'db'
    # volumes:
    #   - ./app/src:/code # get from folder, not image
    secrets:
      - db-password
    networks:
      - csnet
    environment:
      - FLASK_APP=app.py

  # React, nginx
  web:
    container_name: web
    build: ./web
    restart: always
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    networks:
      - csnet
    

  adminer:
    image: adminer
    restart: always
    networks:
      - csnet
    ports: 
      - 8080:8080
    depends_on:
      - db



volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  csnet: