version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - csnet
    environment: #sets up the database
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  app:
    build: app
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./app/src:/code # get from folder, not image
    secrets:
      - db-password
    networks:
      - csnet

  adminer:
    image: adminer
    restart: always
    networks:
      - csnet
    ports: 
     - 8080:8080



volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  csnet: